global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'tp-foyer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['tp-foyer:9090']  # Port 9090 is the actuator port defined in tp-foyer service
