apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: spring-boot-app
  type: NodePort  # Use LoadBalancer if deploying to a cloud provider
